version: '3.6'
services:
  pgdb:
    # postgres:12.3
    image: postgres@sha256:222c12ec1601f38cee2c84fd044756e32815cf11ce36151735c37cb4ead60855
    environment:
      POSTGRES_USER: authpass
      POSTGRES_PASSWORD: blubb
      POSTGRES_DB: authpass
    volumes:
#      - ./_data/pgdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./_data/pgdb/data:/var/lib/postgresql/data
    command: >
      postgres
      -c log_min_duration_statement=100
      -c log_checkpoints=on
      -c log_connections=on
      -c log_disconnections=on
      -c log_lock_waits=on
      -c log_temp_files=0
      -c log_autovacuum_min_duration=0
      -c log_error_verbosity=default
      -c log_line_prefix='%t [%3p]: [%2l] db=%d,user=%u,app=%a,client=%h '
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 30
        window: 120s
      placement:
        constraints: [node.role == manager]
    stop_grace_period: 60s
  backend:
    image: docker.pkg.github.com/msgsrv/msgserv/msgserv-backend
    #image: hpoul/authpass-backend-test
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - buildnumber
        - hostinfo=${USER}@${HOST}
    ports:
      - 9560:8080
    command: /msgserv_backend.exe serve -c config/prod.yaml
    volumes:
      - ./config:/config
    depends_on:
      - pgdb
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3000
        window: 120s
      update_config:
        delay: 30s
        order: start-first
        monitor: 5m
        failure_action: rollback
  dev:
    image: google/dart:2.9-dev
    depends_on:
      - pgdb
    volumes:
      - ..:/src
    deploy:
      replicas: 0

