name: msgserve_backend
description: MsgServe HTTP backend.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  openapi_base: ^2.0.0
  args: ^2.0.0
  json_annotation: ^4.9.0
  msgserve_shared:
    path: ../msgserve_shared
  postgres_utils:
    path: ../../deps/postgres_utils.dart
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.8
  build_runner: ^2.1.2
  json_serializable: ^6.9.5

dependency_overrides:
#  openapi_base:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_base
#  openapi_code_builder:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_code_builder
