name: msgserv_backend
description: MsgServ HTTP backend.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  openapi_base: ^0.2.0
  args: ^2.0.0
  json_annotation: ^4.0.1
  msgserv_shared:
    path: ../msgserv_shared
  postgres_utils:
    path: ../../deps/postgres_utils.dart
  uuid: ^3.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.10.0
  json_serializable: ^4.1.0

dependency_overrides:
#  openapi_base:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_base
#  openapi_code_builder:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_code_builder
