name: build backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: create build number
      id: buildnumber
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: |
        buildnumber=$(curl -s https://raw.githubusercontent.com/hpoul/git-buildnumber/v1.0/git-buildnumber.sh | bash /dev/stdin generate)
        echo "::set-output name=buildnumber::$buildnumber"
    - name: docker build
      run: cd docker && docker-compose build backend
    - uses: azure/docker-login@v1
      with:
        login-server: 'docker.pkg.github.com'
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      run: cd docker && docker-compose push backend
    - name: extract executable from image
      run: |
        image=$( docker create docker.pkg.github.com/msgserve/msgserve/msgserve-backend )
        docker cp ${image}:/msgserve_backend.exe .
        docker rm ${image}
    - uses: actions/upload-artifact@v4
      with:
        name: msgserve_backend_${{ steps.buildnumber.outputs.buildnumber }}
        path: msgserve_backend.exe
